import styled from 'styled-components'

const OtherDynamic = styled.div`
    display:flex;
    flex-direction:column;
    height:100%;
    background:#fff;
    >div:nth-child(1){
        flex:1;
        overflow-y:scroll;
        .showcloak,.showcloak2{
        position:absolute;
        z-index: 100;
        width:100%;
        height:100%;
        background:#5D5C5C;
        opacity:.55;
    }
    .blacklist{
        position:absolute;
        z-index: 101;
        top:.30rem;
        right:.2rem;
        width:1.1rem;
        height:.79rem;
        background:#fff;
        border-bottom-left-radius:.2rem;
        border-bottom-right-radius:.2rem;
        border-top-left-radius:.2rem;
        display:flex;
        flex-direction:column;
        align-items:center;
        p{
            height:.3rem;
            line-height:.3rem;
            font-size:.16rem;
        }
        p:nth-child(1){
            margin-top:.1rem;
            color:red;
        }
    }
    .showbigpic{
        position:absolute;
        z-index: 100;
        left:50%;
        top:50%;
        transform:translate(-50%,-50%);
        width:2.2rem;
        height:2.9rem;
        display:flex;
        flex-direction:column;
        align-items:center;
        img{
            width:2.2rem;
            height:2.2rem;
            border-radius:50%;
        }
        p{
            margin-top:.1rem;
            width:2rem;
            height: .4rem;
            background:#89C3EB;
            font-size:.2rem;
            color:#fff;
            border-radius:.2rem;
            text-align:center;
            line-height:.4rem;
        }
    }
    header{
        height:2.73rem;
        position: relative;
        border-bottom-left-radius:.3rem;
        border-bottom-right-radius:.3rem;
        background:url('https://ss0.bdstatic.com/70cFvHSh_Q1YnxGkpoWK1HF6hhy/it/u=2089088284,3944731500&fm=26&gp=0.jpg');
        background-size:100% 100%;
        .top{
            height:.44rem;
            background:rgba(255,255,255,0.5);
            align-items:center;
            display:flex;
            img:nth-child(1){
                width:.16rem;
                height:.16rem;
                margin-left:.2rem
            }
            img:nth-child(2){
                width:.2rem;
                height:.2rem;
                margin-left:3.05rem;
            }
        }
        .info{
            position:absolute;
            width:1.5rem;
            left:50%;
            top:50%;
            transform:translate(-50%,-50%);
            display:flex;
            flex-direction:column;
            align-items:center;
            justify-content:center;
            color:#fff;
            img{
                width:.94rem;
                height:.94rem;
                border-radius:50%;
            }
            p:nth-child(2){
                font-size:.2rem;
            }
            p:nth-child(3){
                text-align:center;
                font-size:.15rem;
                width:100%;
                white-space:nowrap;
                overflow:hidden;
                text-overflow:ellipsis;
            }
            
        }
        .fans{
            position:absolute;
            width:1.05rem;
            height:.48rem;
            background:#fff;
            left:50%;
            bottom:-.24rem;
            transform:translateX(-50%);
            border-radius:.3rem;
            display:flex;
            z-index:99;
            div:nth-child(1){
                margin-left:.18rem;
            }
            div:nth-child(2){
                margin-left:.18rem;
            }
        }
    }
    main{
        .dynamic{
            height:2.78rem;
            position:relative;
            /* overflow:hidden; */
            padding-top:.1rem;
            .all{
                margin-left:.55rem;
                border-radius:.15rem;
                width:3rem;
                height:2.53rem;
                box-shadow:0 .03rem .06rem rgba(178,178,178,0.16);
                padding-left:.15rem;
                .time{
                    margin-top:.1rem;
                    color:#707070;
                    font-size:.14rem;
                }
                .content{
                    margin-top:.1rem;
                    color:#090909;
                    font-size:.16rem;
                }
                .pic{
                    width:2.6rem;
                    height:1.56rem;
                }
                .more{
                    margin-top:.1rem;
                    height:.18rem;
                    display:flex;
                    align-items:center;
                    img{
                        width:.14rem;
                        height:.14rem;
                        margin-right:.03rem;
                    }
                    .commit{
                        margin-left:.17rem;
                    }
                }
            }
            .xian{
                height:2.73rem;
                position:absolute;
                left:0;
                top:0;
                img:nth-child(1){
                    position:absolute;
                    left:.06rem;
                    width:.34rem;
                    height:.34rem;
                }
                img:nth-child(2){
                   height:2.88rem;
                   margin-left:.18rem;
                }
            }
        }
    }
    }
    
    footer{
        height:.44rem;
        display:flex;
        color:#fff;
        display:flex;
        align-items:center;
        div{
            margin-left:.8rem;
            background:#89C3EB;
            width:.6rem;
            height:.23rem;
            border-radius:.15rem;
            line-height:.23rem;
            text-align:center;
        }
        div:nth-child(1){
            display:flex;
            img{
                margin-top:.05rem;
                margin-left:.05rem;
                width:.14rem;
                height:.14rem;
            }
        }
    }
`
export{
    OtherDynamic
}